tests/intel/xe_madvise: Fix armhf compilation
There are a compiler errors on armhf, related to a cast from pointer
to uint64_t:

../tests/intel/xe_madvise.c:201:20: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  201 |  igt_assert_eq_u64((uint64_t)ptr, (uint64_t)MAP_FAILED);
      |                    ^

Fix it by using igt_assert_eq_ptr() macro.

Cc: Arvind Yadav <arvind.yadav@intel.com>
Cc: Nishit Sharma <nishit.sharma@intel.com>
Cc: "Zbigniew Kempczyński" <zbigniew.kempczynski@intel.com>
Fixes: 42d669fde782 ("tests/intel/xe_madvise: Add purged-mmap-blocked subtest")
Signed-off-by: Kamil Konieczny <kamil.konieczny@linux.intel.com>
Reviewed-by: Karthik B S <karthik.b.s@intel.com>